### ISSUE TITLE
Mismatched quotes in readme for maven repo entry for gradle

### ISSUE THREAD

**Issue by muksihs** [RHazDev/IPFS-Daemon#1]
maven { url 'https://mymavenrepo.com/repo/NIp3fBk55f5oF6VI1Wso/" }
=>
maven { url "https://mymavenrepo.com/repo/NIp3fBk55f5oF6VI1Wso/" }

**Comment by Hazae41** [comment]
Fixed in https://github.com/RHazDev/IPFS-Daemon/commit/9530e59b76019f7e5ebff0c8186f2bd4288d3bc6
